FROM node:20-alpine
RUN npm install -g typescript ts-node ts-lint
WORKDIR /usr/src/app
COPY ./sih-atellica-qplus-backend/package*.json ./
RUN npm install npm -g
RUN npm install
COPY ./sih-atellica-qplus-backend .
COPY ./certificates ../certificates
EXPOSE 8080
CMD ["npm", "run", "docker-dev"]
