FROM node:14-alpine
RUN npm install -g typescript ts-node ts-lint
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install npm -g
RUN npm install
COPY . .
EXPOSE 8080
CMD ["npm", "run", "docker-dev"]
